run:
  concurrency: 4
  deadline: 1m
  issues-exit-code: 1
  tests: true
issues:
  exclude-dirs:
    - model
  exclude-files:
    - assets.go
linters:
  enable:
    - bodyclose
    - errcheck
    - gosec
    - govet
    - nilerr
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - unused
