run:
  concurrency: 4
  deadline: 1m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - model
  skip-files:
    - assets.go
linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gocritic
    - lll
    - unparam
    - funlen
