version: 2

common_steps:
  - &restore_dependencies
    key: spool-modules-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ checksum "go.sum" }}
  - &save_dependencies
    key: spool-modules-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ checksum "go.sum" }}
    paths:
      - /go/pkg/mod
  - &restore_tools
    key: spool-tools-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ checksum "go.sum" }}
  - &save_tools
    key: spool-tools-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ checksum "go.sum" }}
    paths:
      - .bin
  - &restore_build_cache
    key: spool-build-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ .Branch }}-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}
  - &save_build_cache
    key: spool-build-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ .Branch }}-{{ .Environment.CIRCLE_BUILD_NUM }}
    paths:
      - /tmp/go/cache

jobs:
  setup:
    docker:
      - image: golang:1.17-stretch
    working_directory: /go/src/github.com/cloudspannerecosystem/spool
    steps:
      - checkout
      - restore_cache: *restore_dependencies
      - restore_cache: *restore_tools
      - run:
          name: download modules and install tools
          command: |
            go mod download
            make install
      - save_cache: *save_dependencies
      - save_cache: *save_tools

  lint:
    docker:
      - image: golang:1.17-stretch
    working_directory: /go/src/github.com/cloudspannerecosystem/spool
    steps:
      - checkout
      - restore_cache: *restore_dependencies
      - restore_cache: *restore_tools
      - run:
            name: run lint
            command: make lint

  test:
    docker:
      - image: golang:1.17-stretch
        environment:
          GOCACHE: /tmp/go/cache
    working_directory: /go/src/github.com/cloudspannerecosystem/spool
    steps:
      - checkout
      - restore_cache: *restore_dependencies
      - restore_cache: *restore_tools
      - restore_cache: *restore_build_cache
      - run:
          name: build
          command: |
            mkdir -p $GOCACHE
            mkdir -p .bin
            go build -o .bin/spool ./cmd/spool
      - save_cache: *save_build_cache
      - run:
          name: run test
          command: make test

workflows:
  version: 2
  build-workflow:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup
